services:
  mortgage-refinery:
    build: .
    container_name: mortgage-refinery
    restart: unless-stopped  # Keep running for continuous polling
    env_file:
      - .env
    volumes:
      # Persist rate tracking state between restarts
      - rate-state:/tmp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  rate-state: